package com.test.test.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "Foo")
public class Foo {

  @DynamoDBHashKey @DynamoDBAutoGeneratedKey private String id;

  @DynamoDBAttribute private String bar;

  public Foo(String bar) {
    this.bar = bar;
  }
}
